name: Rust - Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Prerequisites
        run: npm install -D tailwindcss
      - name: Run Clippy
        run: cargo clippy -- -D warnings --no-deps --workspace